from django.conf.urls import url
from . import views



urlpatterns = [
    url(r'^verify/$',views.verify,name='verify'),
    url(r'^infrastructure/$',views.InfrastructureView.as_view(),name='infrastructure'),
    url(r'^about/$',views.AboutView.as_view(),name='index'),
    url(r'^contact/$',views.ContactView.as_view(),name='contact'),
    url(r'^activities/$',views.ActivityView.as_view(),name='activity'),
    url(r'^events/$',views.EventView.as_view(),name='events'),
    url(r'^studentlife/$',views.StudentLifeView.as_view(),name='studentlife'),
    url(r'^careers/$',views.CareerView.as_view(),name='career'),
    url(r'^admissions/$',views.AdmissionView.as_view(),name='admission'),
    url(r'^acheivements/$',views.AcheivementView.as_view(),name='acheivement'),
    url(r'^aboutme/$',views.AboutmeView.as_view(),name='aboutme'),
    url(r'^$',views.HomeView.as_view(),name = 'home'),
    url(r'^blog/',views.PostListView.as_view(),name = 'post_list'),
    url(r'^post/(?P<pk>\d+)/$',views.PostDetailView.as_view(),name = 'post_detail'),
    url(r'^post/new/$',views.CreatePostView.as_view(),name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$',views.PostUpdateView.as_view(),name = 'post_edit'),
    url(r'^drafts/$',views.DraftListView.as_view(),name = 'post_draft_list'),
    url(r'^post/(?P<pk>\d+)/remove/$',views.PostDeleteView.as_view(),name='post_remove'),
    url(r'^post/(?P<pk>\d+)/publish/$',views.post_publish,name= 'post_publish'),
    url(r'^updates/$',views.UpdatesListView.as_view(),name= 'update_list'),
    url(r'^updates/new/$',views.CreateUpdatesView.as_view(),name = 'update_new'),
    url(r'^updates/(?P<pk>\d+)/remove/$',views.UpdatesDeleteView.as_view(),name= 'update_delete'),
    url(r'^faculty/new/$',views.CreateFacultyView.as_view(),name = 'faculty_new'),
    url(r'^faculty/$',views.FacultyListView.as_view(),name = 'faculty_list'),
    url(r'^faculty/(?P<pk>\d+)/edit/$',views.FacultyUpdateView.as_view(), name = 'faculty_edit'),
    url(r'^faculty/(?P<pk>\d+)/remove/$',views.FacultyDeleteView.as_view(), name = 'faculty_delete'),
    url(r'^videos/$',views.CreateGallaryView.as_view(),name='gallary_new'),
    url(r'^videos/(?P<pk>\d+)/remove/$',views.GallaryDeleteView.as_view(),name='gallary_delete'),
    url(r'^gallary/$',views.GallaryListView.as_view(),name='gallary_list'),
    url(r'^faq/new/$',views.CreateFaqView.as_view(),name='faq_new'),
    url(r'^faq/(?P<pk>\d+)/remove/$',views.FaqDeleteView.as_view(),name='faq_delete'),
    url(r'^faq/(?P<pk>\d+)/edit/$',views.FaqUpdateView.as_view(),name='faq_edit'),
    url(r'^faq/$',views.FaqListView.as_view(),name='faq_list'),
    url(r'^exam_list/$',views.ExamListView.as_view(),name='exam_list'),
    url(r'^exam/(?P<pk>\d+)/$',views.ExamDetailView.as_view(),name='exam_detail'),
    url(r'^exam/new/$',views.CreateExamView.as_view(),name='exam_new'),
    url(r'^exam/(?P<pk>\d+)/remove',views.ExamDeleteView.as_view(),name='exam_delete'),
    url(r'^exam/(?P<pk>\d+)/acheiver/$',views.add_achiever_to_exam,name='add_acheiver_to_exam'),
    url(r'^acheiver/(?P<pk>\d+)/remove/$',views.acheiver_delete,name='acheiver_delete'),
    url(r'^section_list/$',views.SectionListView.as_view(),name='section_list'),
    url(r'^section/(?P<pk>\d+)/$',views.SectionDetailView.as_view(),name='section_detail'),
    url(r'^section/new/$',views.CreateSectionView.as_view(),name='section_new'),
    url(r'^section/(?P<pk>\d+)/remove/$',views.SectionDeleteView.as_view(),name='section_delete'),
    url(r'^section/(?P<pk>\d+)/student/$',views.add_student_to_section,name='add_student_to_section'),
    url(r'^student/(?P<pk>\d+)/delete/$',views.student_delete,name='student_delete'),
    url(r'^change_password/$',views.change_password,name='change_password'),
    url(r'^sendrequest/$',views.sendingrequest,name='sendrequest'),
    url(r'^alumni_list/$',views.AlumniListView.as_view(),name='alumni_list'),
    url(r'^alumni/(?P<pk>\d+)$', views.AlumniDetailView.as_view(), name='alumni_detail'),
    url(r'^alumni/new/$', views.CreateAlumniView.as_view(), name='alumni_new'),
    url(r'^alumni/(?P<pk>\d+)/edit/$', views.AlumniUpdateView.as_view(), name='alumni_edit'),
    url(r'^alumni/(?P<pk>\d+)/remove/$', views.AlumniDeleteView.as_view(), name='alumni_remove'),
    url(r'^alumni/(?P<pk>\d+)/publish/$', views.alumni_publish, name='alumni_publish'),
    url(r'^alumni/(?P<pk>\d+)/student/$', views.add_alumnistudent_to_alumni, name='add_alumnistudent_to_alumni'),
    url(r'^alumnistudent/(?P<pk>\d+)/approve/$', views.alumnistudent_approve, name='alumnistudent_approve'),
    url(r'^alumnistudent/(?P<pk>\d+)/remove/$', views.alumnistudent_remove, name='alumnistudent_remove'),
    url(r'^download/(?P<path>.*)$',views.download,name='download')

]
