# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='faculty_experience',
            field=models.IntegerField(default=0),
        ),
    ]
