# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0005_section_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallary',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gallary',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='gallary',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
