# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0008_auto_20171116_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallary',
            name='video',
            field=models.FileField(upload_to=''),
        ),
    ]
