# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0010_auto_20171116_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallary',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
