# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0015_auto_20171117_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnistudent',
            old_name='post',
            new_name='alumni',
        ),
    ]
