# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0016_auto_20171117_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnistudent',
            name='alumni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnistudents', to='schoolapp.Alumni'),
        ),
    ]
