# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0017_auto_20171117_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallary',
            name='video',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
