# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-02 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0019_auto_20171203_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnistudent',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
